//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Riplayer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RIPLAYER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDR_POPMENU                     131
#define IDD_RECORD                      132
#define IDD_SETENCODE                   133
#define IDD_INFO                        134
#define IDD_PLAYVEDIO                   135
#define IDD_LOGIN                       136
#define IDD_VOICE                       137
#define IDD_VEDIO                       138
#define IDD_STREAM                      139
#define IDD_SET                         140
#define IDI_ICON1                       141
#define IDI_ICON2                       142
#define IDI_ICON3                       143
#define IDI_ICON4                       144
#define IDD_PICTURE                     145
#define IDR_JPG3                        156
#define IDR_JPG7                        157
#define IDR_JPG4                        158
#define IDR_JPG5                        159
#define IDR_JPG6                        160
#define IDR_JPG8                        163
#define IDR_JPG_PLAY                    164
#define IDR_JPG_PLAY1                   165
#define IDR_JPG_STOP                    169
#define IDR_JPG_PICTURE                 170
#define IDR_JPG_RECORD                  171
#define IDR_JPG_VOICE                   172
#define IDR_JPG_SLIDER                  173
#define IDR_JPG_PAUSE                   175
#define IDR_JPG_STOP1                   176
#define IDR_JPG_PICTURE1                177
#define IDR_JPG_RECORD1                 178
#define IDR_JPG_PAUSE1                  179
#define IDR_JPG_VOICE1                  180
#define IDR_JPG_CLOSE                   181
#define IDR_JPG2                        182
#define IDR_JPG1                        183
#define IDR_JPG_MAX                     184
#define IDR_JPG_MIN                     185
#define IDR_JPG_MIN1                    186
#define IDR_JPG_MAX1                    187
#define IDR_JPG_CLOSE1                  188
#define IDR_JPG_MUTE                    189
#define IDR_JPG_MUTE1                   190
#define IDR_JPG_BTN1                    192
#define IDR_JPG_BTN1_1                  193
#define IDR_JPG_DIALOG1                 196
#define IDR_JPG_DIALOG2                 197
#define IDR_JPG_BTN2                    198
#define IDR_JPG_BTN2_2                  199
#define IDR_JPG_SLIDER0                 200
#define IDR_JPG_NORM1                   201
#define IDR_JPG_NORM                    202
#define IDR_JPG_ORIG                    203
#define IDR_JPG_ORIG1                   204
#define IDR_MENU_TRAY                   205
#define IDR_MENU2                       206
#define IDR_POPMENUE_ENLISH             210
#define IDR_MENU1_ENGLISH               211
#define IDR_MENU2_ENGLISH               212
#define IDD_ABOUTDLG                    214
#define IDR_JPG_DISPLAY                 238
#define IDR_JPG_BAR                     239
#define IDR_JPG_ICON                    259
#define IDI_MAINFRAME                   266
#define IDR_MENUBK                      271
#define IDR_HELPMENU                    272
#define IDR_MEDIAMENU                   273
#define IDR_TOOLMENU                    274
#define IDD_MESSAGEBOXDLG               277
#define IDD_TIPDIALOG                   284
#define IDR_CLOSEX                      287
#define IDR_CLOSEX1                     288
#define IDR_ABOUT                       289
#define IDR_RECSTOP1                    290
#define IDR_RECSTOP                     291
#define IDI_ICON5                       300
#define IDC_BTN_PAUSE                   1004
#define IDC_BTN_STOP                    1005
#define IDC_SLIDER2                     1006
#define IDC_SLIDER                      1006
#define IDC_MUTE                        1007
#define IDC_BTN_SLIENCE                 1007
#define IDC_EDIT2                       1009
#define IDC_BROWSE                      1010
#define IDC_EDIT4                       1010
#define IDC_PICTURE                     1011
#define IDC_RECORD                      1012
#define IDC_CANCEL                      1013
#define IDC_IPADDRESS1                  1020
#define IDC_CONNECT                     1021
#define IDC_SETTING                     1022
#define IDC_EDIT1                       1023
#define IDC_COMBO1                      1024
#define IDC_EDIT5                       1024
#define IDC_EDIT3                       1025
#define IDC_BUTTON3                     1026
#define IDC_COMBO2                      1027
#define IDC_PLAY                        1027
#define IDC_COMBO3                      1028
#define IDC_URL                         1028
#define IDC_COMBO4                      1029
#define IDC_STATIC_VIEW                 1029
#define IDC_COMBO5                      1030
#define IDC_BTN_RECORD                  1031
#define IDC_BTN_PICTURE                 1032
#define IDC_EDIT_OUTPUT                 1035
#define IDC_BUTTON4                     1036
#define IDC_BUTTON1                     1036
#define IDC_BUTTON5                     1037
#define IDC_BUTTON6                     1038
#define IDC_BUTTON7                     1039
#define IDC_BUTTON8                     1040
#define IDC_BUTTON2                     1047
#define IDC_STATIC_RECT                 1052
#define IDC_LIST1                       1056
#define IDC_STATIC1                     1057
#define IDC_STATIC2                     1058
#define IDC_STATIC3                     1059
#define IDC_STATIC4                     1060
#define IDC_STATIC6                     1061
#define IDC_STATIC_TIP1                 1062
#define IDC_STATIC5                     1062
#define IDC_STATIC_TIP2                 1063
#define IDC_STATIC81                    1063
#define IDC_STATIC7                     1064
#define IDC_STATIC9                     1065
#define IDC_IPADDRESS                   1068
#define IDM_OPEN                        32771
#define IDM_EXIT                        32772
#define IDC_BTN_PLAY                    32774
#define IDM_PSP                         32778
#define IDM_SETENCODE                   32779
#define IDM_INFO                        32780
#define IDM_ABOUT                       32781
#define IDM_LICENSE                     32782
#define IDM_SCREEN                      32783
#define IDM_ORIGINAL                    32784
#define IDM_SMALL                       32785
#define IDM_LARGE                       32786
#define IDM_SETP                        32789
#define IDM_SETR                        32790
#define IDM_HTC3                        32791
#define IDM_HTC2                        32792
#define IDM_HTC1                        32793
#define IDM_HTC4                        32794
#define ID_MRU_CLR                      32795
#define IDM_FULLSCREEN                  32796
#define IDR_MENU_SHOW                   32797
#define IDR_MENU_EXIT                   32798
#define IDR_CHINESE                     32803
#define IDR_ENGLISH                     32804
#define IDM_STOPRECROD                  32807
#define IDM_OPENFILE                    32808
#define IDR_CLEARMENU                   33264

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
